### ISSUE TITLE
极好的观察对象

### ISSUE THREAD

**Issue by KojiTadokoro114** [postyizhan/lezi-wiki#19]
https://www.minebbs.com/threads/26441/

正方：低素质哥，中文变量名大蛇
反方：喵厨，地图炮专家，低素质哥，ddos大蛇

此资料为二手，可能出现断章取义的情况，希望有当事人进行补充

**Comment by KojiTabosh** [comment]
更新：果然是断章取义，建议入《典》
聊天详细内容见QQ群

**Comment by postyizhan** [comment]
聊天详细内容在哪里
![图片](https://github.com/postyizhan/lezi-wiki/assets/97342038/647e57e3-38a6-404a-9609-db8f1c1ff299)
