### ISSUE TITLE
能使得我屁股脱落的脑残仓库

### ISSUE THREAD

**Issue by lim114514** [postyizhan/lezi-wiki#2]
不怕DMCA？不怕国内举报？还是你认为挂Gitee绑定手机号不怕被晶哥轮了？

**Comment by pingguomc** [comment]
诶呦，这不是说要DDOS别人网站的那个吗

**Comment by pingguomc** [comment]
对不起，我可能认错人了。
sorry

**Comment by lim114514** [comment]
1. 开这个issues只是为了好玩
2. 我在乐子wiki写东西的时候你还在折腾你的retard server
